/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function Earth(props) {
  const { nodes, materials } = useGLTF('earth/earth.gltf')

  const mesh = useRef()
  useFrame(({ clock }) => { 
    mesh.current.rotation.y += 0.001
  }) 

  return (
    <group {...props} dispose={null} ref={mesh}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['moon.001']} scale={2.5} />
      </group>
    </group>
  )
}

useGLTF.preload('/earth.gltf')
export default Earth;