/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: porn8712377 (https://sketchfab.com/porn8712377)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/earth-f2e03160786c4213b0b137dc3cabe8d1
title: Earth
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'


type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
  }
  materials: {
    moon: THREE.MeshStandardMaterial
  }
}

export function Earth(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/earth/scene.gltf') as unknown as GLTFResult;

  const group = useRef();

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[-1.7, -1.5, 0]} scale={1.75}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.moon} />
      </group>
    </group>
  )
}

useGLTF.preload('/earth/scene.gltf')

export default Earth;
